# Generated by Django 4.2.5 on 2023-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('SubscriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
